name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build the article PDF
    permissions: write-all
    concurrency: showyourwork-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0s

      - name: Build the article PDF
        id: build
        with:
          conda-cache-number: 1
          showyourwork-spec: git+https://github.com/showyourwork/showyourwork
        uses: showyourwork/showyourwork-action@main
        env:
          SANDBOX_TOKEN: ${{ secrets.SANDBOX_TOKEN }}
          OVERLEAF_TOKEN: ${{ secrets.OVERLEAF_TOKEN }}
